name: Build School Bell EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019 # Windows 7 호환성을 위한 구버전 빌드 환경

    steps:
    - name: 저장소 코드 가져오기
      uses: actions/checkout@v4

    - name: Python 3.8 설정
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' # Windows 7을 지원하는 파이썬 버전

    - name: 필수 패키지 설치
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: 포터블 EXE 빌드
      run: |
        pyinstaller --noconfirm --onefile --windowed main.py

    - name: 빌드된 EXE 파일 업로드
      uses: actions/upload-artifact@v4
      with:
        name: SchoolBell-Win7
        path: dist/*.exe